/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define APPARMOR_CACHE_DIR "/data/lindroid/lxc/cache"

#define DEFAULT_CGROUP_PATTERN ""

#define ENABLE_COVERITY_BUILD 1

#define ENFORCE_MEMFD_REXEC 1

#define ENFORCE_THREAD_SAFETY 1

#define HAVE_APPARMOR 0

#define HAVE_BPF 0

#define HAVE_CLOSE_RANGE 1

#define HAVE_COMPILER_ATTR_FALLTHROUGH 1

#define HAVE_COMPILER_ATTR_NONNULL 1

#define HAVE_COMPILER_ATTR_RETURNS_NONNULL 1

#define HAVE_DBUS 0

#define HAVE_DECL_SECCOMP_NOTIFY_FD 0

#define HAVE_DECL_SECCOMP_SYSCALL_RESOLVE_NAME_ARCH 1

#define HAVE_ENDMNTENT 1

#define HAVE_EXECVEAT 1

#define HAVE_FACCESSAT 1

#define HAVE_FEXECVE 1

#define HAVE_FGETLN 0

#define HAVE_FMEMOPEN 1

#define HAVE_FSCONFIG 0

#define HAVE_FSCONFIG_SET_FLAG 0

#define HAVE_FSMOUNT 0

#define HAVE_FSOPEN 0

#define HAVE_FSPICK 1

#define HAVE_FS_CONFIG_SET_BINARY 0

#define HAVE_FS_CONFIG_SET_CMD_CREATE 0

#define HAVE_FS_CONFIG_SET_CMD_RECONFIGURE 0

#define HAVE_FS_CONFIG_SET_PATH_EMPTY 0

#define HAVE_FS_CONFIG_SET_PATH_FD 0

#define HAVE_FS_CONFIG_SET_STRING 0

#define HAVE_GETGRGID_R 1

#define HAVE_GETLINE 1

#define HAVE_GETSUBOPT 1

#define HAVE_GETTID 1

#define HAVE_HASMNTOPT 1

#define HAVE_KCMP 0

#define HAVE_KEYCTL 0

#define HAVE_LIBCAP 0

#define HAVE_LIBURING 0

#define HAVE_MEMFD_CREATE 1

#define HAVE_MOUNT_SETATTR 0

#define HAVE_MOVE_MOUNT 0

#define HAVE_OPENAT2 0

#define HAVE_OPENPTY 1

#define HAVE_OPENSSL 0

#define HAVE_OPEN_TREE 0

#define HAVE_PAM 0

#define HAVE_PERSONALITY 1

#define HAVE_PIDFD_OPEN 0

#define HAVE_PIDFD_SEND_SIGNAL 0

#define HAVE_PIVOT_ROOT 0

#define HAVE_PRLIMIT 1

#define HAVE_PRLIMIT64 1

#define HAVE_PTHREAD_SETCANCELSTATE 1

#define HAVE_PTY_H 1

#define HAVE_RAND_R 1

#define HAVE_RENAMEAT2 1

#define HAVE_SCMP_FILTER_CTX 0

#define HAVE_SECCOMP 0

#define HAVE_SELINUX 0

#define HAVE_SETHOSTNAME 1

#define HAVE_SETMNTENT 1

#define HAVE_SETNS 1

#define HAVE_SIGDESCR_NP 0

#define HAVE_SIGNALFD 1

#define HAVE_STATIC_LIBCAP 0

#define HAVE_STATVFS 1

#define HAVE_STATX 1

#define HAVE_STRCHRNUL 1

#define HAVE_STRERROR_R 1

#define HAVE_STRLCAT 1

#define HAVE_STRLCPY 1

#define HAVE_STRUCT_CLONE_ARGS 1

#define HAVE_STRUCT_MOUNT_ATTR 1

#define HAVE_STRUCT_OPEN_HOW 1

#define HAVE_STRUCT_RTNL_LINK_STATS64 1

#define HAVE_STRUCT_SECCOMP_NOTIF_SIZES 1

#define HAVE_SYS_MEMFD_H 0

#define HAVE_SYS_PERSONALITY_H 1

#define HAVE_SYS_PIDFD_H 1

#define HAVE_SYS_RESOURCE_H 1

#define HAVE_SYS_SIGNALFD_H 1

#define HAVE_SYS_TIMERFD_H 1

#define HAVE_UNSHARE 1

#define HAVE_UTMPX_H 1

#define HAVE___ALIGNED_U64 1

#define IS_BIONIC 1

#define LIBCAP_SUPPORTS_FILE_CAPABILITIES 1

#define LIBEXECDIR "/system/libexec"

#define LOGPATH "/data/lindroid/lxc/log"

#define LXCINITDIR "/system/libexec"

#define LXCPATH "/data/lindroid/lxc"

#define LXCROOTFSMOUNT "/data/lindroid/lxc/rootfs"

#define LXCTEMPLATECONFIG "/data/lindroid/lxc/config"

#define LXCTEMPLATEDIR "/data/linfroid/lxc/templates"

#define LXC_DEFAULT_CONFIG "/system/lindroid/lxc/default.conf"

#define LXC_GLOBAL_CONF "/system/lindroid/lxc/lxc.conf"

#define LXC_USERNIC_CONF "/system/lindroid/lxc/lxc-usernet"

#define LXC_USERNIC_DB "/data/lindroid/lxc/nics"

#define RUNTIME_PATH "/data/lindroid/lxc/run"

#define SBINDIR "/system/sbin"

#define STRERROR_R_CHAR_P 1

#define _FILE_OFFSET_BITS 64

#define _GNU_SOURCE

#define _LINUX_MOUNT_H

#define __STDC_FORMAT_MACROS

